name = "bolt-ai"
pages_build_output_dir = "./build/client"

[vars]
NODE_VERSION = "20"

[site]
bucket = "./build/client"

[[headers]]
for = "/*"
[headers.values]
  Cross-Origin-Opener-Policy = "same-origin"
  Cross-Origin-Embedder-Policy = "require-corp"